//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Christoc.Modules.DisplayPlugg {
    
    
    public partial class EditComponents {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Plugghest.Modules.UserControl.DisplayPlugg.Label.Edit1 label;
        
        /// <summary>
        /// latex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Plugghest.Modules.UserControl.DisplayPlugg.Latex.Edit1 latex;
        
        /// <summary>
        /// RichRichText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Plugghest.Modules.UserControl.DisplayPlugg.RichRichText.Edit1 RichRichText;
        
        /// <summary>
        /// RichText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Plugghest.Modules.UserControl.DisplayPlugg.RichText.Edit RichText;
        
        /// <summary>
        /// YouTube control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Plugghest.Modules.UserControl.DisplayPlugg.YouTube.Edit1 YouTube;
    }
}
